package rentalmobil404;

import java.awt.Color;
import javax.swing.JPanel;

public class Home extends javax.swing.JFrame {

    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        buttonDaftarMobil = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonPenyewaan = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buttonPengembalian = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        buttonLogout = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        buttonKelolaAkun = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        buttonRiwayat = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 81, 221));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Rental Mobil 404");

        buttonDaftarMobil.setBackground(new java.awt.Color(0, 81, 221));
        buttonDaftarMobil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonDaftarMobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDaftarMobilMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonDaftarMobilMousePressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_mobil.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Daftar Mobil");

        javax.swing.GroupLayout buttonDaftarMobilLayout = new javax.swing.GroupLayout(buttonDaftarMobil);
        buttonDaftarMobil.setLayout(buttonDaftarMobilLayout);
        buttonDaftarMobilLayout.setHorizontalGroup(
            buttonDaftarMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonDaftarMobilLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buttonDaftarMobilLayout.setVerticalGroup(
            buttonDaftarMobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonDaftarMobilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(buttonDaftarMobilLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonPenyewaan.setBackground(new java.awt.Color(0, 81, 221));
        buttonPenyewaan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonPenyewaan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonPenyewaanMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonPenyewaanMousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_penyewaan.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Penyewaan");

        javax.swing.GroupLayout buttonPenyewaanLayout = new javax.swing.GroupLayout(buttonPenyewaan);
        buttonPenyewaan.setLayout(buttonPenyewaanLayout);
        buttonPenyewaanLayout.setHorizontalGroup(
            buttonPenyewaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPenyewaanLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buttonPenyewaanLayout.setVerticalGroup(
            buttonPenyewaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPenyewaanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPenyewaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPenyewaanLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        buttonPengembalian.setBackground(new java.awt.Color(0, 81, 221));
        buttonPengembalian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonPengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonPengembalianMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonPengembalianMousePressed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(0, 81, 221));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Pengembalian");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_keyboardreturn.png"))); // NOI18N
        jLabel11.setText("jLabel11");

        javax.swing.GroupLayout buttonPengembalianLayout = new javax.swing.GroupLayout(buttonPengembalian);
        buttonPengembalian.setLayout(buttonPengembalianLayout);
        buttonPengembalianLayout.setHorizontalGroup(
            buttonPengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPengembalianLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buttonPengembalianLayout.setVerticalGroup(
            buttonPengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPengembalianLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        buttonLogout.setBackground(new java.awt.Color(0, 81, 221));
        buttonLogout.setMinimumSize(new java.awt.Dimension(0, 0));
        buttonLogout.setPreferredSize(new java.awt.Dimension(210, 58));
        buttonLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonLogoutMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonLogoutMousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Logout");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_logout.png"))); // NOI18N

        javax.swing.GroupLayout buttonLogoutLayout = new javax.swing.GroupLayout(buttonLogout);
        buttonLogout.setLayout(buttonLogoutLayout);
        buttonLogoutLayout.setHorizontalGroup(
            buttonLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonLogoutLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buttonLogoutLayout.setVerticalGroup(
            buttonLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonLogoutLayout.createSequentialGroup()
                .addGroup(buttonLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                .addContainerGap())
        );

        buttonKelolaAkun.setBackground(new java.awt.Color(0, 81, 221));
        buttonKelolaAkun.setMinimumSize(new java.awt.Dimension(0, 0));
        buttonKelolaAkun.setPreferredSize(new java.awt.Dimension(210, 58));
        buttonKelolaAkun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonKelolaAkunMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonKelolaAkunMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Kelola Akun");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_manageaccounts.png"))); // NOI18N

        javax.swing.GroupLayout buttonKelolaAkunLayout = new javax.swing.GroupLayout(buttonKelolaAkun);
        buttonKelolaAkun.setLayout(buttonKelolaAkunLayout);
        buttonKelolaAkunLayout.setHorizontalGroup(
            buttonKelolaAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonKelolaAkunLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buttonKelolaAkunLayout.setVerticalGroup(
            buttonKelolaAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(buttonKelolaAkunLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonKelolaAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(buttonKelolaAkunLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        buttonRiwayat.setBackground(new java.awt.Color(0, 81, 221));
        buttonRiwayat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonRiwayat.setPreferredSize(new java.awt.Dimension(210, 58));
        buttonRiwayat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonRiwayatMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonRiwayatMousePressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Riwayat");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ic_time.png"))); // NOI18N

        javax.swing.GroupLayout buttonRiwayatLayout = new javax.swing.GroupLayout(buttonRiwayat);
        buttonRiwayat.setLayout(buttonRiwayatLayout);
        buttonRiwayatLayout.setHorizontalGroup(
            buttonRiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonRiwayatLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buttonRiwayatLayout.setVerticalGroup(
            buttonRiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonRiwayatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonRiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonDaftarMobil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonPenyewaan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonPengembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addContainerGap(40, Short.MAX_VALUE))
            .addComponent(buttonLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
            .addComponent(buttonKelolaAkun, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
            .addComponent(buttonRiwayat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel7)
                .addGap(33, 33, 33)
                .addComponent(buttonDaftarMobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(buttonPenyewaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonPengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(buttonRiwayat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(buttonKelolaAkun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(buttonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(280, Short.MAX_VALUE))
        );

        buttonPengembalian.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 910));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1270, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 1270, 930));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPengembalianMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPengembalianMousePressed
        setColor(buttonPengembalian);
        resetColor(buttonDaftarMobil);
        resetColor(buttonPenyewaan);
        resetColor(buttonRiwayat);
        resetColor(buttonKelolaAkun);
        resetColor(buttonLogout);
    }//GEN-LAST:event_buttonPengembalianMousePressed

    private void buttonPenyewaanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPenyewaanMousePressed
        setColor(buttonPenyewaan);
        resetColor(buttonDaftarMobil);
        resetColor(buttonPengembalian);
        resetColor(buttonRiwayat);
        resetColor(buttonKelolaAkun);
        resetColor(buttonLogout);
    }//GEN-LAST:event_buttonPenyewaanMousePressed

    private void buttonDaftarMobilMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDaftarMobilMousePressed
        setColor(buttonDaftarMobil);
        resetColor(buttonPengembalian);
        resetColor(buttonPenyewaan);
        resetColor(buttonRiwayat);
        resetColor(buttonKelolaAkun);
        resetColor(buttonLogout);
    }//GEN-LAST:event_buttonDaftarMobilMousePressed

    private void buttonPenyewaanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPenyewaanMouseClicked
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        Penyewaan sewa = new Penyewaan();
        sewa.setVisible(true);
        jDesktopPane1.add(sewa);
    }//GEN-LAST:event_buttonPenyewaanMouseClicked

    private void buttonDaftarMobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDaftarMobilMouseClicked
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        DaftarMobil dm = new DaftarMobil();
        dm.setVisible(true);
        jDesktopPane1.add(dm);
    }//GEN-LAST:event_buttonDaftarMobilMouseClicked

    private void buttonPengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPengembalianMouseClicked
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        Pengembalian p = new Pengembalian();
        p.setVisible(true);
        jDesktopPane1.add(p);
    }//GEN-LAST:event_buttonPengembalianMouseClicked

    private void buttonLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLogoutMouseClicked
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        this.dispose();
        Login L = new Login();
        L.setVisible(true);
    }//GEN-LAST:event_buttonLogoutMouseClicked

    private void buttonKelolaAkunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonKelolaAkunMouseClicked
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        User U = new User();
        U.setVisible(true);
        jDesktopPane1.add(U);
    }//GEN-LAST:event_buttonKelolaAkunMouseClicked

    private void buttonRiwayatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRiwayatMouseClicked
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        Riwayat rw = new Riwayat();
        rw.setVisible(true);
        jDesktopPane1.add(rw);
    }//GEN-LAST:event_buttonRiwayatMouseClicked

    private void buttonRiwayatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRiwayatMousePressed
        setColor(buttonRiwayat);
        resetColor(buttonPengembalian);
        resetColor(buttonPenyewaan);
        resetColor(buttonDaftarMobil);
        resetColor(buttonKelolaAkun);
        resetColor(buttonLogout);
    }//GEN-LAST:event_buttonRiwayatMousePressed

    private void buttonKelolaAkunMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonKelolaAkunMousePressed
        setColor(buttonKelolaAkun);
        resetColor(buttonPengembalian);
        resetColor(buttonPenyewaan);
        resetColor(buttonDaftarMobil);
        resetColor(buttonRiwayat);
        resetColor(buttonLogout);
    }//GEN-LAST:event_buttonKelolaAkunMousePressed

    private void buttonLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLogoutMousePressed
        setColor(buttonLogout);
        resetColor(buttonPengembalian);
        resetColor(buttonPenyewaan);
        resetColor(buttonDaftarMobil);
        resetColor(buttonRiwayat);
        resetColor(buttonKelolaAkun);
    }//GEN-LAST:event_buttonLogoutMousePressed

    void setColor(JPanel panel){
        panel.setBackground(new Color(0,58, 158)); 
    }
    
    void resetColor(JPanel panel){
        panel.setBackground(new Color(0,81,221)); 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonDaftarMobil;
    private javax.swing.JPanel buttonKelolaAkun;
    private javax.swing.JPanel buttonLogout;
    private javax.swing.JPanel buttonPengembalian;
    private javax.swing.JPanel buttonPenyewaan;
    private javax.swing.JPanel buttonRiwayat;
    public static javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public void admin() {
        buttonDaftarMobil.setVisible(true);
        buttonPenyewaan.setVisible(true);
        buttonPengembalian.setVisible(true);
        buttonRiwayat.setVisible(true);
        buttonKelolaAkun.setVisible(true);
        buttonLogout.setVisible(true);
    }

    public void user() {
        buttonDaftarMobil.setVisible(false);
        buttonPenyewaan.setVisible(true);
        buttonPengembalian.setVisible(false);
        buttonRiwayat.setVisible(false);
        buttonKelolaAkun.setVisible(false);
        buttonLogout.setVisible(true);
    }
    
}
